In [1]:
import pandas as pd

In [5]:
invoice = pd.read_csv("InvoiceData2.txt")
invoice.head()

,InvoiceLineID,CustomerCode,TransactionID,Description,Year,Month,Day,PackageTypeID,Quantity,Sales,TotalDryItems,TotalChillerItems
0,1,832,12126,Ride on toy sedan car (Black) 1/12 scale,2018,1,1,7,10,2300,1,0
1,2,803,15342,Developer joke mug - old C developers never di...,2018,1,1,7,9,117,2,0
2,3,803,15342,USB food flash drive - chocolate bar,2018,1,1,7,9,288,2,0
3,4,105,12211,Superhero action jacket (Blue) XXL,2018,1,1,7,3,90,1,0
4,5,57,17129,Permanent marker black 5mm nib (Black) 5mm,2018,1,1,7,96,288,3,0

In [6]:
len(invoice)

228265

In [7]:
invoice.isnull().sum()

InvoiceLineID        0
CustomerCode         0
TransactionID        0
Description          0
Year                 0
Month                0
Day                  0
PackageTypeID        0
Quantity             0
Sales                0
TotalDryItems        0
TotalChillerItems    0
dtype: int64

In [8]:
import duckdb

In [11]:
query = """
SELECT 
    InvoiceLineID,
    CustomerCode,
    TransactionID,
    Description,
    MAKE_DATE(Year, Month, Day) AS Date,
    Year,
    Month,
    Day,
    PackageTypeID,
    Quantity,
    Sales,
    TotalDryItems,
    TotalChillerItems
FROM read_csv_auto('C:/Users/ekadw/Documents/GitHub/Battlefield/PowerBI/Power_BI_tutorial_For_Beginners/InvoiceData2.txt')
"""

#SELECT * 
#FROM read_csv_auto('myfile.txt');

con = duckdb.connect()
df = con.execute(query).fetchdf()
df.head()

,InvoiceLineID,CustomerCode,TransactionID,Description,Date,Year,Month,Day,PackageTypeID,Quantity,Sales,TotalDryItems,TotalChillerItems
0,1,832,12126,Ride on toy sedan car (Black) 1/12 scale,2018-01-01,2018,1,1,7,10,2300,1,0
1,2,803,15342,Developer joke mug - old C developers never di...,2018-01-01,2018,1,1,7,9,117,2,0
2,3,803,15342,USB food flash drive - chocolate bar,2018-01-01,2018,1,1,7,9,288,2,0
3,4,105,12211,Superhero action jacket (Blue) XXL,2018-01-01,2018,1,1,7,3,90,1,0
4,5,57,17129,Permanent marker black 5mm nib (Black) 5mm,2018-01-01,2018,1,1,7,96,288,3,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228265 entries, 0 to 228264
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   InvoiceLineID      228265 non-null  int64
 1   CustomerCode       228265 non-null  int64
 2   TransactionID      228265 non-null  int64
 3   Description        228265 non-null  object
 4   Date               228265 non-null  datetime64[us]
 5   Year               228265 non-null  int64
 6   Month              228265 non-null  int64
 7   Day                228265 non-null  int64
 8   PackageTypeID      228265 non-null  int64
 9   Quantity           228265 non-null  int64
 10  Sales              228265 non-null  int64
 11  TotalDryItems      228265 non-null  int64
 12  TotalChillerItems  228265 non-null  int64
dtypes: datetime64[us](1), int64(11), object(1)
memory usage: 22.6+ MB

In [13]:
df.to_csv('InvoiceData2.txt')

In [14]:
df.Date.max()

Timestamp('2021-05-31 00:00:00')

In [15]:
df.Date.min()

Timestamp('2018-01-01 00:00:00')

In [16]:
print((0.84)**(25))

0.012793287257602606

In [22]:
import math

def combination(n, r):
    return math.factorial(n) // (math.factorial(r) * math.factorial(n - r))

p = 1/combination(50, 7)
q = 1-p
qq = 1-(q**300)
Ex = 1/qq
result = Ex/104
print(result)

3201.427878432648

In [23]:
print(p)

1.0011573378825924e-08

In [24]:
print(q)

0.9999999899884267