In [2]:
import polars as pl
import pandas as pd
import duckdb

In [7]:
stock_market = """
SELECT 
    *,
    filename() AS source,
    regexp_extract(filename(), '[^/]+$') AS ticker
FROM read_csv_auto('C:/Users/ekadw/Documents/DATA/Stock_Market/stocks/*.csv')
"""

con = duckdb.connect()
stock_market_A = con.execute(stock_market).fetchdf()
stock_market_A.head()

CatalogException: Catalog Error: Scalar Function with name filename does not exist!
Did you mean "finalize"?

LINE 4:     filename() AS source,
            ^

In [3]:
print(duckdb.__version__)

1.4.0

In [10]:
import duckdb
con = duckdb.connect()
# A simple test with a known small CSV
con.execute("""
SELECT
  *,
  filename() AS fname,
  regexp_extract(filename(), '([^/]+)\\.parquet$') AS tick
FROM read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2009\yellow_taxi_2009\*.parquet')
""").fetchdf()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 117-118: truncated \UXXXXXXXX escape (2197939854.py, line 4)

In [22]:
import duckdb

con = duckdb.connect()

query = """
WITH CTE_filename AS (
SELECT 
    *,
    regexp_extract(filename, '([^/\\\\]+)\\.parquet$') AS source
FROM read_parquet('C:/Users/ekadw/Documents/DATA/Example/csv_to_parquet_multiple_folders', filename=true)
)
SELECT
    *,
    regexp_extract(source, '[^/]+$',0) AS ticker
FROM CTE_filename
"""

stock_market_A = con.execute(query).fetchdf()
stock_market_A.head()

,Month,Taxi,Amount,filename,source,ticker
0,April,A,100,C:\Users\ekadw\Documents\DATA\Example\csv_to_p...,taxi_a_april_2019.parquet,taxi_a_april_2019.parquet
1,April,A,200,C:\Users\ekadw\Documents\DATA\Example\csv_to_p...,taxi_a_april_2019.parquet,taxi_a_april_2019.parquet
2,April,A,300,C:\Users\ekadw\Documents\DATA\Example\csv_to_p...,taxi_a_april_2019.parquet,taxi_a_april_2019.parquet
3,April,B,100,C:\Users\ekadw\Documents\DATA\Example\csv_to_p...,taxi_b_april_2019.parquet,taxi_b_april_2019.parquet
4,April,B,200,C:\Users\ekadw\Documents\DATA\Example\csv_to_p...,taxi_b_april_2019.parquet,taxi_b_april_2019.parquet

In [7]:
import duckdb
con = duckdb.connect()

query = """
WITH CTE_filename AS (
SELECT
    *,
    regexp_extract(filename, '([^/\\\\]+)\\.parquet$') AS source,
    regexp_extract(filename, '([^/\\\\]+)\\.parquet$', 1) AS ticker
FROM read_parquet('C:/Users/ekadw/Documents/DATA/Example/csv_to_parquet_multiple_folders/*/*.parquet', filename=true)
)
SELECT
    Month,
    Taxi,
    Amount,
    source,
    ticker
FROM CTE_filename
"""
stock_market_A = con.execute(query).fetchdf()
stock_market_A.head()

   Month Taxi  Amount                     source             ticker
0  April    A     100  taxi_a_april_2019.parquet  taxi_a_april_2019
1  April    A     200  taxi_a_april_2019.parquet  taxi_a_april_2019
2  April    A     300  taxi_a_april_2019.parquet  taxi_a_april_2019
3  April    B     100  taxi_b_april_2019.parquet  taxi_b_april_2019
4  April    B     200  taxi_b_april_2019.parquet  taxi_b_april_2019

In [ ]:
import duckdb
con = duckdb.connect()

query = """
WITH CTE_filename AS (
SELECT
    *,
    regexp_extract(filename, '([^/\\\\]+)\\.parquet$') AS source,
    regexp_extract(filename, '([^/\\\\]+)\\.parquet$', 1) AS ticker
FROM read_parquet('C:/Users/ekadw/Documents/DATA/Example/csv_to_parquet_multiple_folders/*/*.parquet', filename=true)
)
SELECT
    *
FROM CTE_filename
"""
stock_market_A = con.execute(query).fetchdf()
stock_market_A.head()