In [1]:
# Data source: https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

In [2]:
import pandas as pd

# Show all columns
pd.set_option("display.max_columns", None)

In [3]:
house = pd.read_csv("./data/train.csv")

In [4]:
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
# Drop column that empty rows more than 5%

# Set threshold (5%)
threshold = 0.05

# Find ratio of missing values per column
missing_ratio = house.isnull().mean()

# Drop columns where missing % > threshold
house_cleaned = house.drop(columns=missing_ratio[missing_ratio > threshold].index)

print("Dropped columns:", missing_ratio[missing_ratio > threshold].index.tolist())
house_cleaned.head()

Dropped columns: ['LotFrontage', 'Alley', 'MasVnrType', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature']

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,2,548,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,2,460,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,2,608,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,3,642,Y,0,35,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,3,836,Y,192,84,0,0,0,0,0,12,2008,WD,Normal,250000

In [7]:
house_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 69 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  MasVnrArea     1452 non-null   float64
 24  ExterQual      1460 non-null   object
 25  ExterCond      1460 non-null   object
 26  Foundation     1460 non-null   object
 27  BsmtQual       1423 non-null   object
 28  BsmtCond       1423 non-null   object
 29  BsmtExposure   1422 non-null   object
 30  BsmtFinType1   1423 non-null   object
 31  BsmtFinSF1     1460 non-null   int64
 32  BsmtFinType2   1422 non-null   object
 33  BsmtFinSF2     1460 non-null   int64
 34  BsmtUnfSF      1460 non-null   int64
 35  TotalBsmtSF    1460 non-null   int64
 36  Heating        1460 non-null   object
 37  HeatingQC      1460 non-null   object
 38  CentralAir     1460 non-null   object
 39  Electrical     1459 non-null   object
 40  1stFlrSF       1460 non-null   int64
 41  2ndFlrSF       1460 non-null   int64
 42  LowQualFinSF   1460 non-null   int64
 43  GrLivArea      1460 non-null   int64
 44  BsmtFullBath   1460 non-null   int64
 45  BsmtHalfBath   1460 non-null   int64
 46  FullBath       1460 non-null   int64
 47  HalfBath       1460 non-null   int64
 48  BedroomAbvGr   1460 non-null   int64
 49  KitchenAbvGr   1460 non-null   int64
 50  KitchenQual    1460 non-null   object
 51  TotRmsAbvGrd   1460 non-null   int64
 52  Functional     1460 non-null   object
 53  Fireplaces     1460 non-null   int64
 54  GarageCars     1460 non-null   int64
 55  GarageArea     1460 non-null   int64
 56  PavedDrive     1460 non-null   object
 57  WoodDeckSF     1460 non-null   int64
 58  OpenPorchSF    1460 non-null   int64
 59  EnclosedPorch  1460 non-null   int64
 60  3SsnPorch      1460 non-null   int64
 61  ScreenPorch    1460 non-null   int64
 62  PoolArea       1460 non-null   int64
 63  MiscVal        1460 non-null   int64
 64  MoSold         1460 non-null   int64
 65  YrSold         1460 non-null   int64
 66  SaleType       1460 non-null   object
 67  SaleCondition  1460 non-null   object
 68  SalePrice      1460 non-null   int64
dtypes: float64(1), int64(35), object(33)
memory usage: 787.2+ KB

In [8]:
# Do the imputation for missing data where the numerical columns will be imputed by median and the categorical columns will be imputed with the most frequent

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify numerical and categorical columns
num_cols = house_cleaned.select_dtypes(include=["number"]).columns
cat_cols = house_cleaned.select_dtypes(exclude=["number"]).columns

# Define imputers
num_imputer = SimpleImputer(strategy="median").set_output(transform="pandas")
cat_imputer = SimpleImputer(strategy="most_frequent").set_output(transform="pandas")

# Build column transformer
preprocessor_imputer = ColumnTransformer(
    transformers=[
        ("num", num_imputer, num_cols),
        ("cat", cat_imputer, cat_cols)
    ]
).set_output(transform="pandas")

# Create pipeline (optional, useful for ML tasks)
pipeline_imputer = Pipeline(steps=[("preprocessor", preprocessor_imputer)]).set_output(transform="pandas")

# Fit and transform
house_imputed = pipeline_imputer.fit_transform(house_cleaned)

# Convert back to DataFrame
house_imputed = pd.DataFrame(house_imputed, columns=list(num_cols) + list(cat_cols))

In [9]:
house_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 69 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             0 non-null      float64
 1   MSSubClass     0 non-null      float64
 2   LotArea        0 non-null      float64
 3   OverallQual    0 non-null      float64
 4   OverallCond    0 non-null      float64
 5   YearBuilt      0 non-null      float64
 6   YearRemodAdd   0 non-null      float64
 7   MasVnrArea     0 non-null      float64
 8   BsmtFinSF1     0 non-null      float64
 9   BsmtFinSF2     0 non-null      float64
 10  BsmtUnfSF      0 non-null      float64
 11  TotalBsmtSF    0 non-null      float64
 12  1stFlrSF       0 non-null      float64
 13  2ndFlrSF       0 non-null      float64
 14  LowQualFinSF   0 non-null      float64
 15  GrLivArea      0 non-null      float64
 16  BsmtFullBath   0 non-null      float64
 17  BsmtHalfBath   0 non-null      float64
 18  FullBath       0 non-null      float64
 19  HalfBath       0 non-null      float64
 20  BedroomAbvGr   0 non-null      float64
 21  KitchenAbvGr   0 non-null      float64
 22  TotRmsAbvGrd   0 non-null      float64
 23  Fireplaces     0 non-null      float64
 24  GarageCars     0 non-null      float64
 25  GarageArea     0 non-null      float64
 26  WoodDeckSF     0 non-null      float64
 27  OpenPorchSF    0 non-null      float64
 28  EnclosedPorch  0 non-null      float64
 29  3SsnPorch      0 non-null      float64
 30  ScreenPorch    0 non-null      float64
 31  PoolArea       0 non-null      float64
 32  MiscVal        0 non-null      float64
 33  MoSold         0 non-null      float64
 34  YrSold         0 non-null      float64
 35  SalePrice      0 non-null      float64
 36  MSZoning       0 non-null      float64
 37  Street         0 non-null      float64
 38  LotShape       0 non-null      float64
 39  LandContour    0 non-null      float64
 40  Utilities      0 non-null      float64
 41  LotConfig      0 non-null      float64
 42  LandSlope      0 non-null      float64
 43  Neighborhood   0 non-null      float64
 44  Condition1     0 non-null      float64
 45  Condition2     0 non-null      float64
 46  BldgType       0 non-null      float64
 47  HouseStyle     0 non-null      float64
 48  RoofStyle      0 non-null      float64
 49  RoofMatl       0 non-null      float64
 50  Exterior1st    0 non-null      float64
 51  Exterior2nd    0 non-null      float64
 52  ExterQual      0 non-null      float64
 53  ExterCond      0 non-null      float64
 54  Foundation     0 non-null      float64
 55  BsmtQual       0 non-null      float64
 56  BsmtCond       0 non-null      float64
 57  BsmtExposure   0 non-null      float64
 58  BsmtFinType1   0 non-null      float64
 59  BsmtFinType2   0 non-null      float64
 60  Heating        0 non-null      float64
 61  HeatingQC      0 non-null      float64
 62  CentralAir     0 non-null      float64
 63  Electrical     0 non-null      float64
 64  KitchenQual    0 non-null      float64
 65  Functional     0 non-null      float64
 66  PavedDrive     0 non-null      float64
 67  SaleType       0 non-null      float64
 68  SaleCondition  0 non-null      float64
dtypes: float64(69)
memory usage: 787.2 KB

In [10]:
house_imputed.head()

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,PavedDrive,SaleType,SaleCondition
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Example dataframe
df = pd.DataFrame({
    "Age": [25, 30, None, 40, None],
    "Salary": [50000, None, 60000, 55000, None],
    "Gender": ["Male", None, "Female", "Male", None],
    "City": ["NY", "LA", None, "NY", "SF"]
})

# Identify numerical and categorical columns
num_cols = df.select_dtypes(include=["number"]).columns
cat_cols = df.select_dtypes(exclude=["number"]).columns

# Define imputers
num_imputer = SimpleImputer(strategy="median").set_output(transform="pandas")
cat_imputer = SimpleImputer(strategy="most_frequent").set_output(transform="pandas")

# Build column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_imputer, num_cols),
        ("cat", cat_imputer, cat_cols)
    ]
).set_output(transform="pandas")

# Create pipeline
pipeline = Pipeline(steps=[("preprocessor", preprocessor)]).set_output(transform="pandas")

# Fit and transform
df_imputed = pipeline.fit_transform(df)

print(df_imputed.dtypes)
print(df_imputed)

TypeError: '<' not supported between instances of 'NoneType' and 'str'

In [16]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Replace Python None with np.nan
house_cleaned = house_cleaned.replace({None: np.nan})

# Identify numerical and categorical columns
num_cols = house_cleaned.select_dtypes(include=["number"]).columns
cat_cols = house_cleaned.select_dtypes(exclude=["number"]).columns

# Define imputers
num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

# Build column transformer
preprocessor_imputer = ColumnTransformer(
    transformers=[
        ("num", num_imputer, num_cols),
        ("cat", cat_imputer, cat_cols)
    ]
).set_output(transform="pandas")

# Create pipeline
pipeline_imputer = Pipeline(steps=[("preprocessor", preprocessor_imputer)]).set_output(transform="pandas")

# Fit and transform
house_imputed = pipeline_imputer.fit_transform(house_cleaned)

In [17]:
house_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 69 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   num__Id             1460 non-null   float64
 1   num__MSSubClass     1460 non-null   float64
 2   num__LotArea        1460 non-null   float64
 3   num__OverallQual    1460 non-null   float64
 4   num__OverallCond    1460 non-null   float64
 5   num__YearBuilt      1460 non-null   float64
 6   num__YearRemodAdd   1460 non-null   float64
 7   num__MasVnrArea     1460 non-null   float64
 8   num__BsmtFinSF1     1460 non-null   float64
 9   num__BsmtFinSF2     1460 non-null   float64
 10  num__BsmtUnfSF      1460 non-null   float64
 11  num__TotalBsmtSF    1460 non-null   float64
 12  num__1stFlrSF       1460 non-null   float64
 13  num__2ndFlrSF       1460 non-null   float64
 14  num__LowQualFinSF   1460 non-null   float64
 15  num__GrLivArea      1460 non-null   float64
 16  num__BsmtFullBath   1460 non-null   float64
 17  num__BsmtHalfBath   1460 non-null   float64
 18  num__FullBath       1460 non-null   float64
 19  num__HalfBath       1460 non-null   float64
 20  num__BedroomAbvGr   1460 non-null   float64
 21  num__KitchenAbvGr   1460 non-null   float64
 22  num__TotRmsAbvGrd   1460 non-null   float64
 23  num__Fireplaces     1460 non-null   float64
 24  num__GarageCars     1460 non-null   float64
 25  num__GarageArea     1460 non-null   float64
 26  num__WoodDeckSF     1460 non-null   float64
 27  num__OpenPorchSF    1460 non-null   float64
 28  num__EnclosedPorch  1460 non-null   float64
 29  num__3SsnPorch      1460 non-null   float64
 30  num__ScreenPorch    1460 non-null   float64
 31  num__PoolArea       1460 non-null   float64
 32  num__MiscVal        1460 non-null   float64
 33  num__MoSold         1460 non-null   float64
 34  num__YrSold         1460 non-null   float64
 35  num__SalePrice      1460 non-null   float64
 36  cat__MSZoning       1460 non-null   object
 37  cat__Street         1460 non-null   object
 38  cat__LotShape       1460 non-null   object
 39  cat__LandContour    1460 non-null   object
 40  cat__Utilities      1460 non-null   object
 41  cat__LotConfig      1460 non-null   object
 42  cat__LandSlope      1460 non-null   object
 43  cat__Neighborhood   1460 non-null   object
 44  cat__Condition1     1460 non-null   object
 45  cat__Condition2     1460 non-null   object
 46  cat__BldgType       1460 non-null   object
 47  cat__HouseStyle     1460 non-null   object
 48  cat__RoofStyle      1460 non-null   object
 49  cat__RoofMatl       1460 non-null   object
 50  cat__Exterior1st    1460 non-null   object
 51  cat__Exterior2nd    1460 non-null   object
 52  cat__ExterQual      1460 non-null   object
 53  cat__ExterCond      1460 non-null   object
 54  cat__Foundation     1460 non-null   object
 55  cat__BsmtQual       1460 non-null   object
 56  cat__BsmtCond       1460 non-null   object
 57  cat__BsmtExposure   1460 non-null   object
 58  cat__BsmtFinType1   1460 non-null   object
 59  cat__BsmtFinType2   1460 non-null   object
 60  cat__Heating        1460 non-null   object
 61  cat__HeatingQC      1460 non-null   object
 62  cat__CentralAir     1460 non-null   object
 63  cat__Electrical     1460 non-null   object
 64  cat__KitchenQual    1460 non-null   object
 65  cat__Functional     1460 non-null   object
 66  cat__PavedDrive     1460 non-null   object
 67  cat__SaleType       1460 non-null   object
 68  cat__SaleCondition  1460 non-null   object
dtypes: float64(36), object(33)
memory usage: 787.2+ KB