In [1]:
import pandas as pd
from scipy.stats import f_oneway, kruskal
from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing import LabelEncoder

def drop_weak_categorical_features(df, target_col, alpha=0.05, mi_threshold=0.0, drop=True):
    """
    Detect categorical features with weak relation to numeric target
    using ANOVA, Kruskal-Wallis, and Mutual Information.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataframe with categorical features and numeric target
    target_col : str
        Name of the numeric target column
    alpha : float
        Significance level for ANOVA/Kruskal (default=0.05)
    mi_threshold : float
        Minimum Mutual Information score to keep a feature
    drop : bool
        If True, returns dataframe with weak categorical features dropped

    Returns
    -------
    df_clean : pd.DataFrame
        Cleaned dataframe (if drop=True) or original df (if drop=False)
    dropped : list
        List of categorical features flagged as weak
    results : pd.DataFrame
        Table with ANOVA p-values, Kruskal p-values, and MI scores
    """
    y = df[target_col]
    cat_cols = df.select_dtypes(include="object").columns
    results = []

    dropped = []
    for col in cat_cols:
        groups = [y[df[col] == level] for level in df[col].dropna().unique()]
        if len(groups) > 1:  # skip single-level categories
            try:
                f_stat, p_anova = f_oneway(*groups)
            except:
                p_anova = 1.0
            try:
                h_stat, p_kruskal = kruskal(*groups)
            except:
                p_kruskal = 1.0
        else:
            p_anova, p_kruskal = 1.0, 1.0

        # Mutual Information (requires numeric encoding)
        le = LabelEncoder()
        encoded = le.fit_transform(df[col].astype(str))
        mi_score = mutual_info_regression(encoded.reshape(-1, 1), y, random_state=42)[0]

        results.append({"Feature": col, "ANOVA_p": p_anova, "Kruskal_p": p_kruskal, "MI": mi_score})

        if (p_anova > alpha) and (p_kruskal > alpha) and (mi_score <= mi_threshold):
            dropped.append(col)

    results_df = pd.DataFrame(results)

    if drop:
        df_clean = df.drop(columns=dropped)
    else:
        df_clean = df.copy()

    return df_clean, dropped, results_df

In [2]:
# Example dataset
df = pd.DataFrame({
    "Gender": ["M", "F", "F", "M", "M", "F"],
    "Department": ["IT", "HR", "HR", "IT", "Finance", "Finance"],
    "Education": ["Bachelor", "Master", "PhD", "Bachelor", "Master", "PhD"],
    "Target": [40000, 42000, 45000, 47000, 50000, 52000]  # numeric regression target
})

df_clean, dropped, results = drop_weak_categorical_features(df, target_col="Target")

print("Dropped features:", dropped)
print("\nResults table:\n", results)
print("\nCleaned DataFrame:\n", df_clean)

Dropped features: ['Gender', 'Education']

Results table:
       Feature   ANOVA_p  Kruskal_p        MI
0      Gender  0.881292   0.827259  0.000000
1  Department  0.158155   0.180092  0.102778
2   Education  0.667988   0.564718  0.000000

Cleaned DataFrame:
   Department  Target
0         IT   40000
1         HR   42000
2         HR   45000
3         IT   47000
4    Finance   50000
5    Finance   52000

In [3]:
df.head()

  Gender Department Education  Target
0      M         IT  Bachelor   40000
1      F         HR    Master   42000
2      F         HR       PhD   45000
3      M         IT  Bachelor   47000
4      M    Finance    Master   50000

In [8]:
df_clean.head()

  Department  Target
0         IT   40000
1         HR   42000
2         HR   45000
3         IT   47000
4    Finance   50000