In [1]:
import polars as pl

In [5]:
data_2009 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2009\yellow_taxi\yellow_tripdata_2009-01.parquet')
data_2009.head(2)

shape: (2, 18)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ vendor_nam ┆ Trip_Picku ┆ Trip_Dropo ┆ Passenger ┆ … ┆ mta_tax ┆ Tip_Amt ┆ Tolls_Amt ┆ Total_Amt │
│ e          ┆ p_DateTime ┆ ff_DateTim ┆ _Count    ┆   ┆ ---     ┆ ---     ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ e          ┆ ---       ┆   ┆ f64     ┆ f64     ┆ f64       ┆ f64       │
│ str        ┆ str        ┆ ---        ┆ i64       ┆   ┆         ┆         ┆           ┆           │
│            ┆            ┆ str        ┆           ┆   ┆         ┆         ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ VTS        ┆ 2009-01-04 ┆ 2009-01-04 ┆ 1         ┆ … ┆ null    ┆ 0.0     ┆ 0.0       ┆ 9.4       │
│            ┆ 02:52:00   ┆ 03:02:00   ┆           ┆   ┆         ┆         ┆           ┆           │
│ VTS        ┆ 2009-01-04 ┆ 2009-01-04 ┆ 3         ┆ … ┆ null    ┆ 2.0     ┆ 0.0       ┆ 14.6      │
│            ┆ 03:31:00   ┆ 03:38:00   ┆           ┆   ┆         ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴─────────┴───────────┴───────────┘

In [4]:
data_2010 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2010\yellow_taxi\yellow_tripdata_2010-01.parquet')
data_2010.head(2)

shape: (2, 18)
┌───────────┬────────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ vendor_id ┆ pickup_dat ┆ dropoff_d ┆ passenger ┆ … ┆ mta_tax ┆ tip_amoun ┆ tolls_amo ┆ total_amo │
│ ---       ┆ etime      ┆ atetime   ┆ _count    ┆   ┆ ---     ┆ t         ┆ unt       ┆ unt       │
│ str       ┆ ---        ┆ ---       ┆ ---       ┆   ┆ f64     ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str        ┆ str       ┆ i64       ┆   ┆         ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ VTS       ┆ 2010-01-26 ┆ 2010-01-2 ┆ 1         ┆ … ┆ 0.5     ┆ 0.0       ┆ 0.0       ┆ 5.0       │
│           ┆ 07:41:00   ┆ 6         ┆           ┆   ┆         ┆           ┆           ┆           │
│           ┆            ┆ 07:45:00  ┆           ┆   ┆         ┆           ┆           ┆           │
│ DDS       ┆ 2010-01-30 ┆ 2010-01-3 ┆ 1         ┆ … ┆ 0.5     ┆ 0.0       ┆ 0.0       ┆ 16.3      │
│           ┆ 23:31:00   ┆ 0         ┆           ┆   ┆         ┆           ┆           ┆           │
│           ┆            ┆ 23:46:12  ┆           ┆   ┆         ┆           ┆           ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [6]:
data_2011 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2011\yellow_taxi\yellow_tripdata_2011-01.parquet')
data_2011.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 4.18      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:00  ┆ 00:12:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 6.94      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:00  ┆ 00:13:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
data_2011['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ f64         ┆ u32      │
╞═════════════╪══════════╡
│ 0.0         ┆ 1        │
│ null        ┆ 13464996 │
└─────────────┴──────────┘

In [7]:
data_2012 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2012\yellow_taxi\yellow_tripdata_2012-01.parquet')
data_2012.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2012-01-0 ┆ 2012-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 5.9       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:07:56  ┆ 00:12:09  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2012-01-0 ┆ 2012-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 9.5       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:49  ┆ 00:30:01  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
data_2012["airport_fee"].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 13058348 │
└─────────────┴──────────┘

In [10]:
data_2013 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2013\yellow_taxi\yellow_tripdata_2013-01.parquet')
data_2013.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2013-01-0 ┆ 2013-01-0 ┆ 3         ┆ … ┆ 0.0       ┆ 16.0      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:39:00  ┆ 00:55:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2013-01-0 ┆ 2013-01-0 ┆ 5         ┆ … ┆ 0.0       ┆ 4.62      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:12:00  ┆ 00:16:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
data_2013['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 14776617 │
└─────────────┴──────────┘

In [12]:
data_2014 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2014\yellow_taxi\yellow_tripdata_2014-01.parquet')
data_2014.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2014-01-0 ┆ 2014-01-0 ┆ 6         ┆ … ┆ 0.0       ┆ 4.52      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:02:00  ┆ 00:04:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2014-01-0 ┆ 2014-01-0 ┆ 5         ┆ … ┆ 0.0       ┆ 4.55      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:06:00  ┆ 00:09:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
data_2014['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 13782517 │
└─────────────┴──────────┘

In [14]:
data_2015 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2015\yellow_taxi\yellow_tripdata_2015-01.parquet')
data_2015.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2015-01-0 ┆ 2015-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 8.4       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:11:33  ┆ 00:16:48  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-0 ┆ 2015-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 7.3       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:24  ┆ 00:24:20  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
data_2015['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 12741035 │
└─────────────┴──────────┘

In [16]:
data_2016 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2016\yellow_taxi\yellow_tripdata_2016-01.parquet')
data_2016.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2016-01-0 ┆ 2016-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 18.36     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:12:22  ┆ 00:29:14  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2016-01-0 ┆ 2016-01-0 ┆ 2         ┆ … ┆ 0.3       ┆ 10.8      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:41:31  ┆ 00:55:10  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
data_2016['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 10905067 │
└─────────────┴──────────┘

In [18]:
data_2017 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2017\yellow_taxi\yellow_tripdata_2017-01.parquet')
data_2017.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2017-01-0 ┆ 2017-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 7.8       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:05  ┆ 00:37:48  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2017-01-0 ┆ 2017-01-0 ┆ 2         ┆ … ┆ 0.3       ┆ 6.3       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:43:25  ┆ 00:47:42  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
data_2017['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ null        ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 9710820 │
└─────────────┴─────────┘

In [20]:
data_2018 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2018\yellow_taxi\yellow_tripdata_2018-01.parquet')
data_2018.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2018-01-0 ┆ 2018-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 5.8       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:21:05  ┆ 00:24:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2018-01-0 ┆ 2018-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 15.3      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:44:55  ┆ 01:03:05  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
data_2018['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ 0.0         ┆ 12      │
│ null        ┆ 8760675 │
└─────────────┴─────────┘

In [22]:
# 2019 must convert csv to parquet
# C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\yellow_taxi
data_2019 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\yellow_taxi\yellow_tripdata_2019-01.parquet')
data_2019.head(2)

FileNotFoundError: The system cannot find the file specified. (os error 2): C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\yellow_taxi\yellow_tripdata_2019-01.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

In [ ]:
data_2019['airport_fee'].value_counts()

In [23]:
data_2020 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2020\yellow_taxi\yellow_tripdata_2020-01.parquet')
data_2020.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2020-01-0 ┆ 2020-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.27     ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:28:15  ┆ 00:33:03  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2020-01-0 ┆ 2020-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 12.3      ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:39  ┆ 00:43:04  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
data_2020['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ null        ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 6405008 │
└─────────────┴─────────┘

In [25]:
data_2021 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2021\yellow_taxi\yellow_tripdata_2021-01.parquet')
data_2021.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2021-01-0 ┆ 2021-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.8      ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:30:10  ┆ 00:36:12  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2021-01-0 ┆ 2021-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 4.3       ┆ 0.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:51:20  ┆ 00:52:19  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
data_2021['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 1369764 │
│ 0.0         ┆ 5       │
└─────────────┴─────────┘

In [27]:
data_2022 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\yellow_taxi\yellow_tripdata_2022-01.parquet')
data_2022.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 2.0       ┆ … ┆ 0.3       ┆ 21.95     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:40  ┆ 00:53:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 13.3      ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:33:43  ┆ 00:42:07  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
data_2022['airport_fee'].value_counts()

shape: (4, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ -1.25       ┆ 1051    │
│ null        ┆ 71503   │
│ 1.25        ┆ 158950  │
│ 0.0         ┆ 2232427 │
└─────────────┴─────────┘

In [29]:
data_2023 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\yellow_taxi\yellow_tripdata_2023-01.parquet')
data_2023.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 14.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:10  ┆ 00:40:36  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 16.9      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:55:08  ┆ 01:01:27  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
data_2023['airport_fee'].value_counts()

shape: (4, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 71743   │
│ 0.0         ┆ 2730456 │
│ 1.25        ┆ 260960  │
│ -1.25       ┆ 3607    │
└─────────────┴─────────┘