In [1]:
import polars as pl

In [5]:
data_2009 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2009\yellow_taxi\yellow_tripdata_2009-01.parquet')
data_2009.head(2)

shape: (2, 18)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ vendor_nam ┆ Trip_Picku ┆ Trip_Dropo ┆ Passenger ┆ … ┆ mta_tax ┆ Tip_Amt ┆ Tolls_Amt ┆ Total_Amt │
│ e          ┆ p_DateTime ┆ ff_DateTim ┆ _Count    ┆   ┆ ---     ┆ ---     ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ e          ┆ ---       ┆   ┆ f64     ┆ f64     ┆ f64       ┆ f64       │
│ str        ┆ str        ┆ ---        ┆ i64       ┆   ┆         ┆         ┆           ┆           │
│            ┆            ┆ str        ┆           ┆   ┆         ┆         ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ VTS        ┆ 2009-01-04 ┆ 2009-01-04 ┆ 1         ┆ … ┆ null    ┆ 0.0     ┆ 0.0       ┆ 9.4       │
│            ┆ 02:52:00   ┆ 03:02:00   ┆           ┆   ┆         ┆         ┆           ┆           │
│ VTS        ┆ 2009-01-04 ┆ 2009-01-04 ┆ 3         ┆ … ┆ null    ┆ 2.0     ┆ 0.0       ┆ 14.6      │
│            ┆ 03:31:00   ┆ 03:38:00   ┆           ┆   ┆         ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴─────────┴───────────┴───────────┘

In [4]:
data_2010 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2010\yellow_taxi\yellow_tripdata_2010-01.parquet')
data_2010.head(2)

shape: (2, 18)
┌───────────┬────────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ vendor_id ┆ pickup_dat ┆ dropoff_d ┆ passenger ┆ … ┆ mta_tax ┆ tip_amoun ┆ tolls_amo ┆ total_amo │
│ ---       ┆ etime      ┆ atetime   ┆ _count    ┆   ┆ ---     ┆ t         ┆ unt       ┆ unt       │
│ str       ┆ ---        ┆ ---       ┆ ---       ┆   ┆ f64     ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str        ┆ str       ┆ i64       ┆   ┆         ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ VTS       ┆ 2010-01-26 ┆ 2010-01-2 ┆ 1         ┆ … ┆ 0.5     ┆ 0.0       ┆ 0.0       ┆ 5.0       │
│           ┆ 07:41:00   ┆ 6         ┆           ┆   ┆         ┆           ┆           ┆           │
│           ┆            ┆ 07:45:00  ┆           ┆   ┆         ┆           ┆           ┆           │
│ DDS       ┆ 2010-01-30 ┆ 2010-01-3 ┆ 1         ┆ … ┆ 0.5     ┆ 0.0       ┆ 0.0       ┆ 16.3      │
│           ┆ 23:31:00   ┆ 0         ┆           ┆   ┆         ┆           ┆           ┆           │
│           ┆            ┆ 23:46:12  ┆           ┆   ┆         ┆           ┆           ┆           │
└───────────┴────────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [6]:
data_2011 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2011\yellow_taxi\yellow_tripdata_2011-01.parquet')
data_2011.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 4.18      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:00  ┆ 00:12:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2011-01-0 ┆ 2011-01-0 ┆ 4         ┆ … ┆ 0.0       ┆ 6.94      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:04:00  ┆ 00:13:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
data_2011['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ f64         ┆ u32      │
╞═════════════╪══════════╡
│ 0.0         ┆ 1        │
│ null        ┆ 13464996 │
└─────────────┴──────────┘

In [7]:
data_2012 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2012\yellow_taxi\yellow_tripdata_2012-01.parquet')
data_2012.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2012-01-0 ┆ 2012-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 5.9       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:07:56  ┆ 00:12:09  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2012-01-0 ┆ 2012-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 9.5       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:49  ┆ 00:30:01  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
data_2012["airport_fee"].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 13058348 │
└─────────────┴──────────┘

In [10]:
data_2013 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2013\yellow_taxi\yellow_tripdata_2013-01.parquet')
data_2013.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2013-01-0 ┆ 2013-01-0 ┆ 3         ┆ … ┆ 0.0       ┆ 16.0      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:39:00  ┆ 00:55:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2013-01-0 ┆ 2013-01-0 ┆ 5         ┆ … ┆ 0.0       ┆ 4.62      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:12:00  ┆ 00:16:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
data_2013['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 14776617 │
└─────────────┴──────────┘

In [12]:
data_2014 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2014\yellow_taxi\yellow_tripdata_2014-01.parquet')
data_2014.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2014-01-0 ┆ 2014-01-0 ┆ 6         ┆ … ┆ 0.0       ┆ 4.52      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:02:00  ┆ 00:04:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2014-01-0 ┆ 2014-01-0 ┆ 5         ┆ … ┆ 0.0       ┆ 4.55      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:06:00  ┆ 00:09:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
data_2014['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 13782517 │
└─────────────┴──────────┘

In [14]:
data_2015 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2015\yellow_taxi\yellow_tripdata_2015-01.parquet')
data_2015.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2015-01-0 ┆ 2015-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 8.4       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:11:33  ┆ 00:16:48  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-0 ┆ 2015-01-0 ┆ 1         ┆ … ┆ 0.0       ┆ 7.3       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:24  ┆ 00:24:20  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
data_2015['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 12741035 │
└─────────────┴──────────┘

In [16]:
data_2016 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2016\yellow_taxi\yellow_tripdata_2016-01.parquet')
data_2016.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2016-01-0 ┆ 2016-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 18.36     ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:12:22  ┆ 00:29:14  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2016-01-0 ┆ 2016-01-0 ┆ 2         ┆ … ┆ 0.3       ┆ 10.8      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:41:31  ┆ 00:55:10  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
data_2016['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬──────────┐
│ airport_fee ┆ count    │
│ ---         ┆ ---      │
│ null        ┆ u32      │
╞═════════════╪══════════╡
│ null        ┆ 10905067 │
└─────────────┴──────────┘

In [18]:
data_2017 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2017\yellow_taxi\yellow_tripdata_2017-01.parquet')
data_2017.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ null      ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2017-01-0 ┆ 2017-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 7.8       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:05  ┆ 00:37:48  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2017-01-0 ┆ 2017-01-0 ┆ 2         ┆ … ┆ 0.3       ┆ 6.3       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:43:25  ┆ 00:47:42  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
data_2017['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ null        ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 9710820 │
└─────────────┴─────────┘

In [20]:
data_2018 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2018\yellow_taxi\yellow_tripdata_2018-01.parquet')
data_2018.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2018-01-0 ┆ 2018-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 5.8       ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:21:05  ┆ 00:24:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2018-01-0 ┆ 2018-01-0 ┆ 1         ┆ … ┆ 0.3       ┆ 15.3      ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:44:55  ┆ 01:03:05  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
data_2018['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ 0.0         ┆ 12      │
│ null        ┆ 8760675 │
└─────────────┴─────────┘

In [33]:
# 2019 must convert csv to parquet
# C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\yellow_taxi
data_2019 = pl.read_csv(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\yellow_taxi\yellow_tripdata_2019-03.csv')
data_2019.head(2)

shape: (2, 18)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ tolls_amo ┆ improveme ┆ total_amo ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ nt_surcha ┆ unt       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ rge       ┆ ---       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ ---       │
│          ┆ str       ┆ str       ┆           ┆   ┆           ┆ f64       ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2019-03-0 ┆ 2019-03-0 ┆ 1         ┆ … ┆ 0.0       ┆ 0.3       ┆ 3.8       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:24:41  ┆ 00:25:31  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2         ┆ … ┆ 0.0       ┆ 0.3       ┆ 15.0      ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:27  ┆ 00:36:37  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
data_2019['airport_fee'].value_counts()

In [23]:
data_2020 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2020\yellow_taxi\yellow_tripdata_2020-01.parquet')
data_2020.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ null      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2020-01-0 ┆ 2020-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.27     ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:28:15  ┆ 00:33:03  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2020-01-0 ┆ 2020-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 12.3      ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:39  ┆ 00:43:04  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
data_2020['airport_fee'].value_counts()

shape: (1, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ null        ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 6405008 │
└─────────────┴─────────┘

In [25]:
data_2021 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2021\yellow_taxi\yellow_tripdata_2021-01.parquet')
data_2021.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2021-01-0 ┆ 2021-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 11.8      ┆ 2.5       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:30:10  ┆ 00:36:12  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2021-01-0 ┆ 2021-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 4.3       ┆ 0.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:51:20  ┆ 00:52:19  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
data_2021['airport_fee'].value_counts()

shape: (2, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 1369764 │
│ 0.0         ┆ 5       │
└─────────────┴─────────┘

In [27]:
data_2022 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\yellow_taxi\yellow_tripdata_2022-01.parquet')
data_2022.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 2.0       ┆ … ┆ 0.3       ┆ 21.95     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:35:40  ┆ 00:53:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ 1.0       ┆ … ┆ 0.3       ┆ 13.3      ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:33:43  ┆ 00:42:07  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [28]:
data_2022['airport_fee'].value_counts()

shape: (4, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ -1.25       ┆ 1051    │
│ null        ┆ 71503   │
│ 1.25        ┆ 158950  │
│ 0.0         ┆ 2232427 │
└─────────────┴─────────┘

In [29]:
data_2023 = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\yellow_taxi\yellow_tripdata_2023-01.parquet')
data_2023.head(2)

shape: (2, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 14.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:10  ┆ 00:40:36  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ 1.0       ┆ … ┆ 1.0       ┆ 16.9      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:55:08  ┆ 01:01:27  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [30]:
data_2023['airport_fee'].value_counts()

shape: (4, 2)
┌─────────────┬─────────┐
│ airport_fee ┆ count   │
│ ---         ┆ ---     │
│ f64         ┆ u32     │
╞═════════════╪═════════╡
│ null        ┆ 71743   │
│ 0.0         ┆ 2730456 │
│ 1.25        ┆ 260960  │
│ -1.25       ┆ 3607    │
└─────────────┴─────────┘

In [34]:
data_2023_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\for_hire_vehicle\fhv_tripdata_2023-01.parquet')
data_2023_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00008       ┆ 2023-01-01   ┆ 2023-01-01   ┆ null         ┆ null         ┆ null    ┆ B00008      │
│              ┆ 00:30:00     ┆ 01:00:00     ┆              ┆              ┆         ┆             │
│ B00078       ┆ 2023-01-01   ┆ 2023-01-01   ┆ null         ┆ null         ┆ null    ┆ B00078      │
│              ┆ 00:01:00     ┆ 03:15:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [35]:
data_2022_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\for_hire_vehicle\fhv_tripdata_2022-01.parquet')
data_2022_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00009       ┆ 2022-01-01   ┆ 2022-01-01   ┆ null         ┆ null         ┆ null    ┆ B00009      │
│              ┆ 00:31:00     ┆ 01:05:00     ┆              ┆              ┆         ┆             │
│ B00009       ┆ 2022-01-01   ┆ 2022-01-01   ┆ null         ┆ null         ┆ null    ┆ B00009      │
│              ┆ 00:37:00     ┆ 01:05:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [36]:
data_2021_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2021\for_hire_vehicle\fhv_tripdata_2021-01.parquet')
data_2021_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00009       ┆ 2021-01-01   ┆ 2021-01-01   ┆ null         ┆ null         ┆ null    ┆ B00009      │
│              ┆ 00:27:00     ┆ 00:44:00     ┆              ┆              ┆         ┆             │
│ B00009       ┆ 2021-01-01   ┆ 2021-01-01   ┆ null         ┆ null         ┆ null    ┆ B00009      │
│              ┆ 00:50:00     ┆ 01:07:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [37]:
data_2020_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2020\for_hire_vehicle\fhv_tripdata_2020-01.parquet')
data_2020_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00001       ┆ 2020-01-01   ┆ 2020-01-01   ┆ 264.0        ┆ 264.0        ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 01:44:00     ┆              ┆              ┆         ┆             │
│ B00001       ┆ 2020-01-01   ┆ 2020-01-01   ┆ 264.0        ┆ 264.0        ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 00:47:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [2]:
import polars as pl
data_2019_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\for_hire_vehicle\fhv_tripdata_2019-01.parquet')
data_2019_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ f64     ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00001       ┆ 2019-01-01   ┆ 2019-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 02:51:55     ┆              ┆              ┆         ┆             │
│ B00001       ┆ 2019-01-01   ┆ 2019-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:45:00     ┆ 00:54:49     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [3]:
data_2018_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2018\for_hire_vehicle\fhv_tripdata_2018-01.parquet')
data_2018_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ f64     ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00001       ┆ 2018-01-01   ┆ 2018-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:45:00     ┆ 01:05:55     ┆              ┆              ┆         ┆             │
│ B00001       ┆ 2018-01-01   ┆ 2018-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 01:30:28     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [4]:
data_2017_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2017\for_hire_vehicle\fhv_tripdata_2017-01.parquet')
data_2017_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00001       ┆ 2017-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
│ B00001       ┆ 2017-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [5]:
data_2016_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2016\for_hire_vehicle\fhv_tripdata_2016-01.parquet')
data_2016_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00001       ┆ 2016-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
│ B00001       ┆ 2016-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00001      │
│              ┆ 00:30:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [6]:
data_2015_for_hire = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2015\for_hire_vehicle\fhv_tripdata_2015-01.parquet')
data_2015_for_hire.head(2)

shape: (2, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────┬─────────────┐
│ dispatching_ ┆ pickup_datet ┆ dropOff_date ┆ PUlocationID ┆ DOlocationID ┆ SR_Flag ┆ Affiliated_ │
│ base_num     ┆ ime          ┆ time         ┆ ---          ┆ ---          ┆ ---     ┆ base_number │
│ ---          ┆ ---          ┆ ---          ┆ f64          ┆ f64          ┆ null    ┆ ---         │
│ str          ┆ datetime[ns] ┆ datetime[ns] ┆              ┆              ┆         ┆ str         │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════╪═════════════╡
│ B00013       ┆ 2015-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00013      │
│              ┆ 00:30:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
│ B00014       ┆ 2015-01-01   ┆ 1989-01-01   ┆ null         ┆ null         ┆ null    ┆ B00014      │
│              ┆ 00:28:00     ┆ 00:00:00     ┆              ┆              ┆         ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────┴─────────────┘

In [9]:
data_2014_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2014\green_taxi\green_tripdata_2014-01.parquet')
data_2014_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ null      │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2014-01-0 ┆ 2014-01-0 ┆ N         ┆ … ┆ 14.5      ┆ 2         ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:17:26  ┆ 00:37:11  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2014-01-0 ┆ 2014-01-0 ┆ N         ┆ … ┆ 9.5       ┆ 2         ┆ null      ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:29:12  ┆ 00:37:43  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
data_2015_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2015\green_taxi\green_tripdata_2015-01.parquet')
data_2015_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ null      │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2015-01-0 ┆ 2015-01-0 ┆ N         ┆ … ┆ 25.4      ┆ 1         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:31:10  ┆ 00:50:41  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2015-01-0 ┆ 2015-01-0 ┆ N         ┆ … ┆ 5.8       ┆ 2         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:01:05  ┆ 00:03:30  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
data_2016_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2016\green_taxi\green_tripdata_2016-01.parquet')
data_2016_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2016-01-0 ┆ 2016-01-0 ┆ N         ┆ … ┆ 56.8      ┆ 1         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:17:40  ┆ 00:36:15  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2016-01-0 ┆ 2016-01-0 ┆ N         ┆ … ┆ 29.16     ┆ 1         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:47:37  ┆ 01:18:37  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
data_2017_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2017\green_taxi\green_tripdata_2017-01.parquet')
data_2017_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ null      │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2017-01-0 ┆ 2017-01-0 ┆ N         ┆ … ┆ 3.8       ┆ 1         ┆ 1         ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:23:36  ┆ 00:24:08  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2017-01-0 ┆ 2017-01-0 ┆ N         ┆ … ┆ 4.3       ┆ 2         ┆ 1         ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:21:40  ┆ 00:23:13  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
data_2018_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2018\green_taxi\green_tripdata_2018-01.parquet')
data_2018_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ null      │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2018-01-0 ┆ 2018-01-0 ┆ N         ┆ … ┆ 7.3       ┆ 2         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:50  ┆ 00:24:39  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2018-01-0 ┆ 2018-01-0 ┆ N         ┆ … ┆ 15.8      ┆ 2         ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:30:26  ┆ 00:46:42  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
data_2019_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\green_taxi\green_tripdata_2019-01.parquet')
data_2019_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2018-12-2 ┆ 2018-12-2 ┆ N         ┆ … ┆ 4.3       ┆ 2.0       ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:17:29  ┆ 15:18:57  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2019-01-0 ┆ 2019-01-0 ┆ N         ┆ … ┆ 7.3       ┆ 2.0       ┆ 1.0       ┆ null      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:16  ┆ 00:16:32  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
data_2020_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2020\green_taxi\green_tripdata_2020-01.parquet')
data_2020_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2019-12-1 ┆ 2019-12-1 ┆ N         ┆ … ┆ 4.81      ┆ 1.0       ┆ 1.0       ┆ 0.0       │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:52:30  ┆ 15:54:39  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2020-01-0 ┆ 2020-01-0 ┆ N         ┆ … ┆ 24.36     ┆ 1.0       ┆ 2.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:45:58  ┆ 00:56:39  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
data_2021_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2021\green_taxi\green_tripdata_2021-01.parquet')
data_2021_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2021-01-0 ┆ 2021-01-0 ┆ N         ┆ … ┆ 6.8       ┆ 2.0       ┆ 1.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:15:56  ┆ 00:19:52  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2021-01-0 ┆ 2021-01-0 ┆ N         ┆ … ┆ 16.86     ┆ 1.0       ┆ 1.0       ┆ 2.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:59  ┆ 00:34:44  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
data_2022_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\green_taxi\green_tripdata_2022-01.parquet')
data_2022_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2022-01-0 ┆ 2022-01-0 ┆ N         ┆ … ┆ 4.8       ┆ 2.0       ┆ 1.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:21  ┆ 00:15:33  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-01-0 ┆ 2022-01-0 ┆ N         ┆ … ┆ 10.8      ┆ 2.0       ┆ 1.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:20:55  ┆ 00:29:38  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
data_2023_green = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\green_taxi\green_tripdata_2023-01.parquet')
data_2023_green.head(2)

shape: (2, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ total_amo ┆ payment_t ┆ trip_type ┆ congestio │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ unt       ┆ ype       ┆ ---       ┆ n_surchar │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ge        │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ ---       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆ f64       │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ N         ┆ … ┆ 24.18     ┆ 1.0       ┆ 1.0       ┆ 2.75      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:26:10  ┆ 00:37:11  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2023-01-0 ┆ 2023-01-0 ┆ N         ┆ … ┆ 15.84     ┆ 1.0       ┆ 1.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:51:03  ┆ 00:57:49  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:

data_2019_hvfhv = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2019\high_volume_for_hire_vehicle\fhvhv_tripdata_2019-02.parquet')
data_2019_hvfhv.head(2)

shape: (2, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ null     │
│           ┆ str       ┆ str       ┆ ns]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B02867    ┆ B02867    ┆ 2019-02-0 ┆ … ┆ N         ┆ N         ┆ N         ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:01:26  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B02879    ┆ B02879    ┆ 2019-02-0 ┆ … ┆ N         ┆ N         ┆ N         ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:26:08  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
data_2020_hvfhv = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2020\high_volume_for_hire_vehicle\fhvhv_tripdata_2020-02.parquet')
data_2020_hvfhv.head(2)

shape: (2, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ ns]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B02872    ┆ B02872    ┆ 2020-01-3 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 23:58:27  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B02872    ┆ B02872    ┆ 2020-02-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:22:32  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
len(data_2020_hvfhv)

21725100

In [22]:
data_2021_hvfhv = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2021\high_volume_for_hire_vehicle\fhvhv_tripdata_2021-02.parquet')
data_2021_hvfhv.head(2)

shape: (2, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ ns]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B02764    ┆ B02764    ┆ 2021-01-3 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 23:59:00  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B02764    ┆ B02764    ┆ 2021-02-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:13:35  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
data_2022_hvfhv = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2022\high_volume_for_hire_vehicle\fhvhv_tripdata_2022-02.parquet')
data_2022_hvfhv.head(2)

shape: (2, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ ns]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-01-3 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 23:58:19  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-02-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:16:14  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
data_2023_hvfhv = pl.read_parquet(r'C:\Users\ekadw\Documents\DATA\NY_Taxi\2023\high_volume_for_hire_vehicle\fhvhv_tripdata_2023-02.parquet')
data_2023_hvfhv.head(2)

shape: (2, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ ns]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2023-02-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:12:17  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2023-02-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:24:45  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
len(data_2023_hvfhv)

17960971